config/routes.rb
Thrillr::Application.routes.draw do

  resources :sessions

  get "/tickets/:id" => "tickets#update"

  resources :users

  resources :movies

  root :to => "movies#index"

  resources :showings

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :showings
  has_many :tickets, :through => :showings
end

app/models/showing.rb
class Showing < ActiveRecord::Base
  attr_accessible :day, :hour, :movie_id

  belongs_to :movie
  has_many :tickets
  has_many :users, :through => :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :showing_id, :price, :seat_number, :user_id

  belongs_to :user
  belongs_to :showing
  has_one :movie, :through => :showing

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

  attr_accessible :email, :name, :password, :password_confirmation

  has_many :tickets
  has_many :showings, :through => :tickets

  validates :email, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
  	if session[:email]
  		@current_user = User.find_by_email(session[:email])
  	end
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
  end

  def create
  end

  def delete
  end

  def edit
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	@user = User.find_by_email(params[:email])
  	if @user.authenticate(params[:password])
  		session[:email] = @user.email
  		redirect_to user_path(@user.id), :notice => "You're logged in:)"
		else

		end
  end

  def destroy
  	session[:email] = nil
    redirect_to root_path, :notice => "You're logged out."
  end

  def new
  end 

end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    @showing = Showing.find(params[:id])
    if !current_user 
      redirect_to movie_path(@showing.movie.id), :notice => "You must be logged in to purchase tickets."
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
  end

  def too_many
  end

  def already_purchased
  end

  def show
  end

  def edit
  end

  def create
  end

  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if current_user.tickets.where(:showing_id => @ticket.showing.id).length > 4
        format.js { render :action => "too_many" } 
      elsif @ticket.user_id == nil
        @ticket.update_attributes(:user_id => current_user.id)
        format.js {render :action => "show" }
      else 
        format.js { render :action => "already_purchased" }
      end
    end
  end

  def delete
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def destroy
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:email] = @user.email
      redirect_to @user
    else
      render action: "new"
    end

  end

  def update
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thrillr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if current_user %>
	Logged in as: <%=link_to current_user.email, user_path(current_user.id) %> 
	<%= link_to "Log out", "/sessions/#{current_user.id}", :method => "delete" %>
<% else %>
	<%= link_to "Sign Up", "/users/new" %>
	<%= link_to "Log in", new_session_path %> 
<% end %>

<%= link_to "All Movies", "/movies" %>

<%= yield %>

</body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/delete.html.erb
<h1>Movies#delete</h1>
<p>Find me in app/views/movies/delete.html.erb</p>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.haml
%p#notice= notice

%h1 Movies playing at Thrillr:

- @movies.each do |movie|
	%ul
		%li
			= link_to movie.name, "/movies/#{movie.id}"
			= movie.description

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

app/views/movies/show.haml
%p#notice= notice

%h1= @movie.name
%h4= @movie.description


%h1 Playing:
Tuesday, July 9 At:
- @movie.showings[0..3].each do |showing|
	%ul
		%li
			= showing.hour
			= link_to "Buy Tickets for this showing", "/showings/#{showing.id}"

Wednesday, July 10 At:
- @movie.showings[4..7].each do |showing|
	%ul
		%li
			= showing.hour
			= link_to "Buy Tickets for this showing", "/showings/#{showing.id}"

Thursday, July 11 At:
- @movie.showings[8..11].each do |showing|
	%ul
		%li
			= showing.hour
			= link_to "Buy Tickets for this showing", "/showings/#{showing.id}"

Friday, July 12 At:
- @movie.showings[12..15].each do |showing|
	%ul
		%li
			= showing.hour
			= link_to "Buy Tickets for this showing", "/showings/#{showing.id}"

Saturday, July 13 At:
- @movie.showings[15..18].each do |showing|
	%ul
		%li
			= showing.hour
			= link_to "Buy Tickets for this showing", "/showings/#{showing.id}"

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>

app/views/showings/create.html.erb
<h1>Showings#create</h1>
<p>Find me in app/views/showings/create.html.erb</p>

app/views/showings/destroy.html.erb
<h1>Showings#destroy</h1>
<p>Find me in app/views/showings/destroy.html.erb</p>

app/views/showings/edit.html.erb
<h1>Showings#edit</h1>
<p>Find me in app/views/showings/edit.html.erb</p>

app/views/showings/index.html.erb
<h1>Showings#index</h1>
<p>Find me in app/views/showings/index.html.erb</p>

app/views/showings/new.html.erb
<h1>Showings#new</h1>
<p>Find me in app/views/showings/new.html.erb</p>

app/views/showings/show.haml
%p#notice= notice

%h1= @showing.movie.name
%h3
	Playing on
	= @showing.day
	At
	= @showing.hour

%em Click on a seat to purchase it.
%br
%em Tickets in yellow have already been purchased.
%br
%br

Number of tickets available: 
=@showing.tickets.where(:user_id => nil).length

%br
Price: $7.00
%br
Seats available: 
%div.all_seats
	-@showing.tickets.sort.each do |ticket|
		%div.seat{:id => "#{ticket.seat_number}"}
			-if ticket.user_id == nil 
				= link_to ticket.seat_number, "/tickets/#{ticket.id}", :remote => true
			-else 
				= ticket.seat_number



%br
%br
%br
= link_to "Back to All Showings for #{@showing.movie.name}", "/movies/#{@showing.movie.id}"

app/views/showings/show.html.erb
<h1>Showings#show</h1>
<p>Find me in app/views/showings/show.html.erb</p>

app/views/showings/update.html.erb
<h1>Showings#update</h1>
<p>Find me in app/views/showings/update.html.erb</p>

app/views/tickets/already_purchased.js.erb
$(document ).ready(function() {

$("h1").prepend("<em>Sorry, this seat has already been purchased! Try another.</em></br>")

});

app/views/tickets/create.html.erb
<h1>Tickets#create</h1>
<p>Find me in app/views/tickets/create.html.erb</p>

app/views/tickets/delete.html.erb
<h1>Tickets#delete</h1>
<p>Find me in app/views/tickets/delete.html.erb</p>

app/views/tickets/edit.html.erb
<h1>Tickets#edit</h1>
<p>Find me in app/views/tickets/edit.html.erb</p>

app/views/tickets/edit.js.erb
<h1>Tickets#edit</h1>
<p>Find me in app/views/tickets/edit.html.erb</p>

app/views/tickets/index.html.erb
<h1>Tickets#index</h1>
<p>Find me in app/views/tickets/index.html.erb</p>

app/views/tickets/new.html.erb
<h1>Tickets#new</h1>
<p>Find me in app/views/tickets/new.html.erb</p>

app/views/tickets/show.html.erb
<h1>Tickets#show</h1>
<p>Find me in app/views/tickets/show.html.erb</p>

app/views/tickets/show.js.erb
$(document ).ready(function() {


$("h1").prepend("<em>Ticket successfully purchased!</em></br>")


$("#<%=@ticket.seat_number%>").text("<%=@ticket.seat_number%>")

});

app/views/tickets/too_many.js.erb
$(document ).ready(function() {

$("h1").prepend("<em>Sorry, you can only purchase up to five tickets for this showing.</em></br>")

});

app/views/tickets/update.html.erb
<h1>Tickets#update</h1>
<p>Find me in app/views/tickets/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up for Thrillr!</h1>

<%= form_for(@user) do |f| %>

	<div class="field">
	  <%= f.label "Name (first and last):" %> <br/>
	  <%= f.text_field :name %>
	</div>

	<div class="field">
	  <%= f.label "Email (this will be your username):" %> <br/>
	  <%= f.text_field :email %>
	</div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up!" %>
  </div>
  
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3> Hi, <%=current_user.name%>! </h3>

<h4> Your Tickets: </h4>

<ul>
	<% current_user.showings.uniq.each do |showing| %>
	<li>
		<%= showing.movie.name %> </br>
		<%= showing.day %>
		<%= showing.hour %> </br>
		<% showing.tickets.where(:user_id => current_user.id).each do |ticket| %>
			<%= ticket.seat_number %>
			<% end %>
		</br>
		<%= link_to "Buy another seat for this showing.", "/showings/#{showing.id}" %>
	</li>	
	</br>
	<% end %>
<ul>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>